apiVersion: v1
kind: Pod
metadata:
  name: test-pod
spec:
  containers:
    - name: test-pod
      image: devcompute.jfrog.io/itsoli-docker-develop-local/demo3-image:latest
      ports:
        - containerPort: 80
